server:
  port: 9000
spring:
  application:
    name: cards
  profiles:
    active: "prod"  #set active profile to prod default
  datasource:
    # docker run -p 3308:3306 --name cardsdb -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=cardsdb -d mysql
    url: jdbc:mysql://localhost:3308/cardsdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: "optional:configserver:http://localhost:8071/" #import configuration from config server using path

management:
  endpoints:
    web:
      exposure:
        include: "*" #expose all actuator endpoints