build:
  version: 3.0

# @configurationProperties example - to read multiple properties from loans.yml at once
loans:
  message: "Welcome to Loans related PROD APIs "
  contactDetails:
    name: "John Doe - PROD Developer"
    email: "john@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345
