services:
  accounts:
    image: "singhsbaghel/accounts:s4"   #image details
    container_name: accounts-ms  # custom name , if not provided random name will be populated by the docker
    ports:
      - "8080:8080"
      #-"8090:8099" if case of multiple port mapping
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ms-bank # common network for microservices, it can be anything
  loans:
    image: "singhsbaghel/loans:s4"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ms-bank
  cards:
    image: "singhsbaghel/cards:s4"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ms-bank
networks:
  ms-bank:
    driver: "bridge" # all microservices are interconnected as they are present in same network