  # [DOC] https://docs.spring.io/spring-cloud-gateway/docs/current/reference/html/

spring:
  application:
    name: gatewayserver
  profiles:
    active: prod
  config:
    import: "optional:configserver:http://localhost:8071/" #import configuration from config server using path
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #enable service discovery
          lowercaseserviceid: true #convert service id to lowercase
      httpclient:               # timeout configuration for gateway for all rest & MS paths
        connect-timeout: 1000   # timeout if gateway was not able to connect to required service in given time
        response-timeout: 5s    # maximum time , gateway will wait for response from service

        # circuit breaker have default/internal timeout in case of MS is not responding. no need any configuration for that
        # CB will return fallback response in case of MS is not responding
        # [doc] Spring cloud gateway -> 12- http timeout configuration -> enable/disable timeout for all or specific routes

management:
  endpoints:
    web:
      exposure:
        include: "*" #expose all actuator endpoints
  endpoint:
    health:
      show-details: always #show detailed health information
    shutdown:
      access: unrestricted
    gateway:
      enabled: true #enable gateway actuator endpoint
  info:
    env:
      enabled: true #enable environment info in actuator info endpoint

endpoints:
  shutdown:
    enabled: true

info:
  app:
    name: "gatewayserver"
    description: "Gateway/Edge Server"
    version: 1.0.0

logging:
  level:
    com:
      gatewayserver: DEBUG #set log level for gatewayserver package to DEBUG

resilience4j.circuitbreaker:
  configs:
    default: # accountsCircuitBreaker:  # can mention multiple configurations -> addnew ->  just use name used in the code
      slidingWindowSize: 10             # how many requests to consider before changing status to open/close
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50          # percentage of failed requests to change status to open
      waitDurationInOpenState: 10000    # time to wait before changing status to half open -> check if service is up

      #http://localhost:8072/actuator/circuitbreakers
      #http://localhost:8072/actuator/circuitbreakers?name=accountsCircuitBreaker -> log of all api request from the application start