  # [DOC] https://docs.spring.io/spring-cloud-gateway/docs/current/reference/html/

spring:
  application:
    name: gatewayserver
  profiles:
    active: prod
  config:
    import: "optional:configserver:http://localhost:8071/" #import configuration from config server using path
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #enable service discovery
          lowercaseserviceid: true #convert service id to lowercase
      httpclient:               # timeout configuration for gateway for all rest & MS paths
        connect-timeout: 1000   # timeout if gateway was not able to connect to required service in given time
        response-timeout: 5s    # maximum time , gateway will wait for response from service

        # circuit breaker have default/internal timeout in case of MS is not responding. no need any configuration for that
        # CB will return fallback response in case of MS is not responding
        # [doc] Spring cloud gateway -> 12- http timeout configuration -> enable/disable timeout for all or specific routes
  data:
    redis:
      connect-timeout: 2s
      host: localhost
      port: 6379
      timeout: 1s     # docker run -p 6379:6379 --name eazyredis -d redis
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:7080/realms/master/protocol/openid-connect/certs"
          # auth server url for accessing certificates during startup. it will download public key certificates from auth server
          # public key certificates are used to validate access token signature -> is token is generated by keycloak server or not.


management:
  endpoints:
    web:
      exposure:
        include: "*" #expose all actuator endpoints
  endpoint:
    health:
      show-details: always #show detailed health information
    shutdown:
      access: unrestricted
    gateway:
      enabled: true #enable gateway actuator endpoint
  info:
    env:
      enabled: true #enable environment info in actuator info endpoint

endpoints:
  shutdown:
    enabled: true

info:
  app:
    name: "gatewayserver"
    description: "Gateway/Edge Server"
    version: 1.0.0

logging:
  level:
    com:
      gatewayserver: DEBUG #set log level for gatewayserver package to DEBUG

resilience4j.circuitbreaker:
  configs:
    default: # accountsCircuitBreaker:  # can mention multiple configurations -> addnew ->  just use name used in the code
      slidingWindowSize: 10             # how many requests to consider before changing status to open/close
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50          # percentage of failed requests to change status to open
      waitDurationInOpenState: 10000    # time to wait before changing status to half open -> check if service is up

      #http://localhost:8072/actuator/circuitbreakers
      #http://localhost:8072/actuator/circuitbreakers?name=accountsCircuitBreaker -> log of all api request from the application start


#resilience4j:
  #  circuitbreaker:
  #    circuitBreakerAspectOrder: 1
  #  retry:
  #    retryAspectOrder: 2

  #lower the higher priority
  # Bulkhead (100) → CircuitBreaker (200) → Retry (300) → RateLimiter (400) → TimeLimiter (500)
  #- resilience4j.retry.retryAspectOrder
  #- resilience4j.circuitbreaker.circuitBreakerAspectOrder
  #- resilience4j.ratelimiter.rateLimiterAspectOrder
  #- resilience4j.timelimiter.timeLimiterAspectOrder
  #- resilience4j.bulkhead.bulkheadAspectOrder