server:
  port: 8090
spring:
  application:
    name: loans
  profiles:
    active: "prod"  #set active profile to prod default
  datasource:
    # docker run -p 3307:3306 --name loansdb -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=loansdb -d mysql
    url: jdbc:mysql://localhost:3307/loansdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always # always recreate the schema using schema.sql {with h2 its not necessury but with mysql it is}
  config:
    import: "optional:configserver:http://localhost:8071/" #import configuration from config server using path

management:
  endpoints:
    web:
      exposure:
        include: "*" #expose all actuator endpoints

