server:
  port: 8080

spring:
  application:
    name: accounts
  profiles:
    active: "prod"  #set active profile to prod default
  h2:
    console:
      enabled: true  #enabled to access the database in browser
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update  #update the schema automatically after program start (schema.sql)
    show-sql: true  #show sql queries in console
  config:
    import: "optional:configserver:http://localhost:8071/" #import configuration from config server using path
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*" #expose all actuator endpoints
