# dependency -> loan/cards/accounts -> configserver -> rabbitmq
services:
  accountsdb:
    container_name: accountsdb
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: accountsdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  loansdb:
    container_name: loansdb
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: loansdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  cardsdb:
    container_name: cardsdb
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: cardsdb
    extends:
      file: common-config.yml
      service: microservice-db-config


  configserver:
    image: "singhsbaghel/configserver:s9"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    extends:
      file: common-config.yml
      service: microservice-base-config

  eurekaserver:
    image: "singhsbaghel/eurekaserver:s9"
    container_name: eurekaserver-ms
    ports:
      - "8070:8070"
    depends_on:
      configserver:
        condition: service_started
    extends:
      file: common-config.yml
      service: microservice-configserver-config
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"

  accounts:
    image: "singhsbaghel/accounts:s9"   #image details
    container_name: accounts-ms         # custom name , if not provided random name will be populated by the docker
    ports:
      - "8080:8080"                     # "8090:8099" if case of multiple port mapping
    environment:
      SPRING_APPLICATION_NAME: "accounts"  # application name
      SPRING_DATASOURCE_URL: "jdbc:mysql://accountsdb:3306/accountsdb"
    depends_on:
      accountsdb:
        condition: service_healthy
      configserver:
        condition: service_started
      eurekaserver:
        condition: service_started
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  loans:
    image: "singhsbaghel/loans:s9"
    container_name: loans-ms
    ports:
      - "8090:8090"
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_DATASOURCE_URL: "jdbc:mysql://loansdb:3306/loansdb"
    depends_on:
      loansdb:
        condition: service_healthy
      configserver:
        condition: service_started
      eurekaserver:
        condition: service_started
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  cards:
    image: "singhsbaghel/cards:s9"
    container_name: cards-ms
    ports:
      - "9000:9000"
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_DATASOURCE_URL: "jdbc:mysql://cardsdb:3306/cardsdb"
    depends_on:
      cardsdb:
        condition: service_healthy
      configserver:
        condition: service_started
      eurekaserver:
        condition: service_started
    extends:
      file: common-config.yml
      service: microservice-eureka-config

networks:
  ms-bank:
    driver: "bridge"                      # all microservices are interconnected as they are present in same network