spring:
  application:
    name: "configserver"
  profiles:
    active: native
  cloud:
    server:
      native:
        #searchLocations: "classpath:/config"
        search-locations: "file:///Users//eazybytes//Documents//config"

server:
  port: 8071


