server:
  port: 9010

spring:
  application:
    name: message
  cloud:
    function:
      definition: email|sms   # compose two function into single logical unit using pipe symbol
    stream:
      bindings:
        emailsms-in-0:  # receiving/looking for the communication request
          destination: send-communication
          group: ${spring.application.name}
        emailsms-out-0:  # sending the communication
          destination: communication-sent
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10s


