server:
  port: 9010

spring:
  application:
    name: message
  cloud:
    function:
      definition: email|sms   # compose two function into single logical unit using pipe symbol
    stream:
      bindings:
        emailsms-in-0:  # receiving/looking for the communication request
          destination: send-communication
          group: ${spring.application.name}
        emailsms-out-0:  # sending the communication
          destination: communication-sent
      kafka:
        binder:
          brokers:
            - localhost:9092
      # kafkalytic plugin to view/analyze the topics


