server:
  port: 8080

spring:
  application:
    name: accounts
  h2:
    console:
      enabled: true  #enabled to access the database in browser
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update  #update the schema automatically after program start (schema.sql)
    show-sql: true  #show sql queries in console
  config:
    import:
      - "application_qa.yml"
      - "application_prod.yml"
#  profiles:
#    active: "qa"                  // manual way to activate profile

#2    way to activate profile while running the application
#2.1 command line way to activate profile - run configuration -> program arguments -> --spring.profiles.active=qa --build.version=1.1
#2.2 jvm system variable way to activate profile - Run configuration -> VM options -> -Dspring.profiles.active=qa -Dbuild.version=1.1
#2.3 environment variable way to activate profile - Run configuration -> Environment variables -> SPRING_PROFILES_ACTIVE=qa;BUILD_VERSION=1.1;
# priority order - command line > jvm system variable > environment variable > application.yml
build:
  version: 0.1

# @configurationProperties example - to read multiple properties from application.yml at once
accounts:
  message: "Welcome to EazyBank accounts related local APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345
