server:
  port: 9000
spring:
  application:
    name: cards
  profiles:
    active: "prod"  #set active profile to prod default
  datasource:
    # docker run -p 3308:3306 --name cardsdb -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=cardsdb -d mysql
    url: jdbc:mysql://localhost:3308/cardsdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: "optional:configserver:http://localhost:8071/" #import configuration from config server using path

management:
  endpoints:
    web:
      exposure:
        include: "*" #expose all actuator endpoints
  endpoint:
    health:
      show-details: always #show detailed health information
    shutdown:
      access: unrestricted #enable shutdown actuator endpoint [whenever service going to deregister from eureka, it will call this endpoint to shutdown the service]
  info:
    env:
      enabled: true #enable environment info in actuator info endpoint

eureka:
  instance:
    prefer-ip-address: true  # register with host hostname instead of ip
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "Cards"
    description: "Cards Service"
    version: 1.0.0

logging:
  level:
    com:
     cards: DEBUG