# dependency -> loan/cards/accounts -> configserver -> rabbitmq
services:
  rabbit:
    image: rabbitmq:4.0-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: common-config.yml
      service: network-deploy-service

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.7
    container_name: keycloak
    ports:
      - "7080:8080"
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
    command: "start-dev"     # keyclock container will start in dev mode and utilize internal db
    extends:
      file: common-config.yml
      service: network-deploy-service

  redis:
    image: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      timeout: 10s
      retries: 10
    extends:
      file: common-config.yml
      service: network-deploy-service

  accountsdb:
    container_name: accountsdb
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: accountsdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  loansdb:
    container_name: loansdb
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: loansdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  cardsdb:
    container_name: cardsdb
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: cardsdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  configserver:
    image: "singhsbaghel/configserver:s13"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    extends:
      file: common-config.yml
      service: microservice-base-config

  eurekaserver:
    image: "singhsbaghel/eurekaserver:s13"
    container_name: eurekaserver-ms
    ports:
      - "8070:8070"
    depends_on:
      configserver:
        condition: service_started
    extends:
      file: common-config.yml
      service: microservice-configserver-config
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"

# excluding ports so services can be accessed present in same docker network - blocked for external access

  accounts:
    image: "singhsbaghel/accounts:s13"   #image details
    container_name: accounts-ms         # custom name , if not provided random name will be populated by the docker
    environment:
      SPRING_APPLICATION_NAME: "accounts"  # application name
      SPRING_DATASOURCE_URL: "jdbc:mysql://accountsdb:3306/accountsdb"
      SPRING_RABBITMQ_HOST: "rabbit"
    depends_on:
      accountsdb:
        condition: service_healthy
      configserver:
        condition: service_started
      eurekaserver:
        condition: service_started
      rabbit:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  loans:
    image: "singhsbaghel/loans:s13"
    container_name: loans-ms
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_DATASOURCE_URL: "jdbc:mysql://loansdb:3306/loansdb"
    depends_on:
      loansdb:
        condition: service_healthy
      configserver:
        condition: service_started
      eurekaserver:
        condition: service_started
    extends:
      file: common-config.yml
      service: microservice-eureka-config


  cards:
    image: "singhsbaghel/cards:s13"
    container_name: cards-ms
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_DATASOURCE_URL: "jdbc:mysql://cardsdb:3306/cardsdb"
    depends_on:
      cardsdb:
        condition: service_healthy
      configserver:
        condition: service_started
      eurekaserver:
        condition: service_started
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  message:
    image: "eazybytes/message:s13"
    container_name: message-ms
    depends_on:
      rabbit:
        condition: service_healthy
    environment:
      SPRING_RABBITMQ_HOST: "rabbit"
    extends:
      file: common-config.yml
      service: network-deploy-service

  gatewayserver:
    image: "singhsbaghel/gatewayserver:s13"
    container_name: gatewayserver-ms
    ports:
      - "8072:8072"
    depends_on:
      accounts:
        condition: service_started
      loans:
        condition: service_started
      cards:
        condition: service_started
      redis:
        condition: service_healthy
    environment:
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI: "http://keycloak:8080/realms/master/protocol/openid-connect/certs"
      SPRING_APPLICATION_NAME: "gatewayserver"
      SPRING_DATA_REDIS_CONNECT-TIMEOUT: 2s
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_TIMEOUT: 1s
    extends:
      file: common-config.yml
      service: microservice-eureka-config

networks:
  ms-bank:
    driver: "bridge"                      # all microservices are interconnected as they are present in same network